### ISSUE TITLE
test

### ISSUE THREAD

**Issue by zero-24** [b2z/jissues-test#17]

**Comment by zero-24** [comment]
test<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/17">jissues.j4devs.ru/jissues-test/17</a>.</sub>

**Comment by zero-24** [comment]
remove label<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/17">jissues.j4devs.ru/jissues-test/17</a>.</sub>

**Comment by b2z** [comment]
oops

**Comment by b2z** [comment]
yea

**Comment by b2z** [comment]
omg<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/17">jissues.j4devs.ru/jissues-test/17</a>.</sub>

**Comment by b2z** [comment]
rtc!

**Comment by b2z** [comment]
fhdf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/17">jissues.j4devs.ru/jissues-test/17</a>.</sub>
